# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Jest tests validation before merging

on:
  pull_request:
    branches: [ "final-backend" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies - Clean Install
      run: npm ci
    - name: Run Jest tests
      env:
        PORT: ${{ secrets.BACKEND_PORT }}
        JWT_SECRET: ${{ secrets.BACKEND_JWT_SECRET }}
      run: npm test
